using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AtidRegister.Models
{
    /// <summary>
    /// Represents conference content (panel, lucture, movie..)
    /// </summary>
    public class Content
    {
        /// <summary>
        /// Unique Content Id, Generated By DB
        /// </summary>
        [Display(Name = "מזהה")]
        public int Id { get; set; }
        /// <summary>
        /// Content Title
        /// </summary>
        [Display(Name = "שם ההרצאה")]
        public string Title { get; set; }
        /// <summary>
        /// Content Description
        /// </summary>
        [Display(Name = "תיאור")]
        public string Description { get; set; }
        /// <summary>
        /// Content Image file name
        /// </summary>
        [Display(Name = "תמונה")]
        public string ImageFile { get; set; }
        /// <summary>
        /// The PK of the content's type
        /// </summary>
        public int TypeId { get; set; }
        /// <summary>
        /// The content's type.
        /// </summary>
        public ContentType Type { get; set; }
        /// <summary>
        /// The PK of the content's time strip.
        /// </summary>
        public int TimeStripId { get; set; }
        /// <summary>
        /// The time strip of the content
        /// </summary>
        public TimeStrip TimeStrip { get; set; }
        /// <summary>
        /// Priority in scheduling
        /// </summary>
        public int SchedulingPriority { get; set; }
        /// <summary>
        /// Maximum amount of paticipants in content
        /// </summary>
        public int SpaceLimitation { get; set; }
        public List<ContentPerson> ContentPeople { get; set; }
        public List<ContentUser> ContentUsers { get; set; }
        public List<UserSchedule> Schedules { get; set; }
    }
}
